# Generated by Django 5.2.3 on 2025-06-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_entrenador', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='pokemon_fotos/')),
            ],
        ),
    ]
