# Generated by Django 5.2.3 on 2025-06-25 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='nombre_entrenador',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(choices=[('F', 'Fuego'), ('A', 'Agua'), ('PL', 'Planta'), ('EL', 'Eléctrico'), ('N', 'Normal')], max_length=2),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.entrenador'),
        ),
    ]
